#!/bin/zsh

#
# ~/.public
#

#
# BEGIN vi
#

_vi() {
  unalias vi &> /dev/null ; \
  unalias vim &> /dev/null ; \
  unalias nvim &> /dev/null ; \
  local _VI_EDITOR
  if which nvim &> /dev/null
  then 
    _VI_EDITOR=$(which nvim)
  elif which vim &> /dev/null
  then
    _VI_EDITOR=$(which vim)
  elif which vi &> /dev/null
  then
    _VI_EDITOR=$(which vi)
  fi
  export EDITOR="${_VI_EDITOR}"
  alias vi="_vi"
  alias vim="_vi"
  alias nvim="_vi"
  ${_VI_EDITOR} ${@:-}
}

alias vi='_vi'
alias vim='_vi'
alias nvim='_vi'

#
# END vi
#

#
# BEGIN mkwip
#

_mkwip() {
  local -r _root="${HOME}/.config/mkwip"
  if [[ ! -e "${_root}" ]]
  then
    echo -n "Enter absolute path of root source: " && \
    read -r _MKWIP_ROOT_SRC && \
    echo -n "Enter absolute path of notes source: " && \
    read -r _MKWIP_NOTES_SRC && \
    echo -n "Enter absolute path of todo source: " && \
    read -r _MKWIP_TODO_SRC && \
    echo -n "Enter absolute path of wip source: " && \
    read -r _MKWIP_WIP_SRC && \
    echo -n "Enter absolute path of destination: " && \
    read -r _MKWIP_DEST && \
    if [[ -z "${EDITOR}" ]]
    then
      echo -n "Enter editor name: " && \
      read -r _MKWIP_EDITOR
    else
      _MKWIP_EDITOR="${EDITOR}"
    fi
    mkdir -p "${_root}"
cat >> "${_root}/mkwip.env" << _EOF
_MKWIP_ROOT_SRC='${_MKWIP_ROOT_SRC}'
_MKWIP_NOTES_SRC='${_MKWIP_NOTES_SRC}'
_MKWIP_TODO_SRC='${_MKWIP_TODO_SRC}'
_MKWIP_WIP_SRC='${_MKWIP_WIP_SRC}'
_MKWIP_DEST='${_MKWIP_DEST}'
_MKWIP_EDITOR='${_MKWIP_EDITOR}'
_EOF
  fi
  source "${_root}/mkwip.env"
  local -r _directory="${_MKWIP_NOTES_SRC}/$(date +%Y)/$(date +%m)/$(date +%d)"
  mkdir -p "${_directory}"
  local -r _file="${_directory}/$(date +%Y-%m-%d).md"
  if [[ ! -e "${_file}" ]]
  then 
    echo "# $(date)" > "${_file}"
  fi
  rm -rf "${_MKWIP_DEST}"
  mkdir -p "${_MKWIP_DEST}"
  local -r _link="${_MKWIP_DEST}"
  ln -sf "${_directory}" "${_MKWIP_DEST}/_$(date +%Y-%m-%d)"
  ln -sf "${_MKWIP_ROOT_SRC}" "${_MKWIP_DEST}/_root"
  ln -sf "${_MKWIP_TODO_SRC}" "${_MKWIP_DEST}/_todo.md"
  ln -sf "${_MKWIP_WIP_SRC}" "${_MKWIP_DEST}/_wip"
}

alias mkwip='_mkwip'

#
# END mkwip
#

#
# BEGIN homebrew
#

_Homebrew_install() {
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
}

_Homebrew_uninstall() {
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  brew list | xargs brew uninstall --force
  brew list --cask | xargs brew uninstall --force
  sudo /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"
  sudo rm -rf /usr/local
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  brew list | xargs brew uninstall --force
  brew list --cask | xargs brew uninstall --force
  sudo /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"
  sudo rm -rf /usr/local
}

_Homebrew_main() {
  case "${1}" in
    "--install")
      _Homebrew_install
    ;;
    "--uninstall")
      _Homebrew_uninstall
    ;;
  esac
}

_homebrew() {
  _Homebrew_main $@
}

alias homebrew='_homebrew'

#
# END homebrew
#