#!/bin/zsh

#
# ~/.public
#

#
# BEGIN vi
#

_vi() {
  unalias vi &> /dev/null ; \
  unalias vim &> /dev/null ; \
  unalias nvim &> /dev/null ; \
  local _VI_EDITOR
  if which nvim &> /dev/null
  then 
    _VI_EDITOR=$(which nvim)
  elif which vim &> /dev/null
  then
    _VI_EDITOR=$(which vim)
  elif which vi &> /dev/null
  then
    _VI_EDITOR=$(which vi)
  fi
  export EDITOR="${_VI_EDITOR}"
  alias vi="_vi"
  alias vim="_vi"
  alias nvim="_vi"
  ${_VI_EDITOR} ${@:-}
}

alias vi='_vi'
alias vim='_vi'
alias nvim='_vi'

#
# END vi
#

#
# BEGIN now
#

_now() {
  [[ -e ~/.env ]] || \
    touch ~/.env && \
  source ~/.env && \
  [[ ! -z ${_NOW_SRC} ]] || \
    (
      echo -n "Enter source directory : " && \
      read -r _NOW_SRC && \
      echo "_NOW_SRC='${_NOW_SRC}'" >> ~/.env
    ) && \
  [[ ! -z ${_NOW_DEST} ]] || \
    (
      echo -n "Enter destination directory : " && \
      read -r _NOW_DEST && \
      echo "_NOW_DEST='${_NOW_DEST}'" >> ~/.env
    ) && \
  source ~/.env && \
  local -r _src="${_NOW_SRC}/$(date +%Y)/$(date +%m)/$(date +%d)"
  local -r _dest="${_NOW_DEST}/$(date +%Y-%m-%d)"
  local -r _file="${_src}/$(date +%Y-%m-%d).md"
  [[ -e "${_src}" ]] || \
    mkdir -p "${_src}" && \
  [[ -e "${_file}" ]] || \
    echo "# $(date)" > "${_file}" && \
  [[ ! -e "${_dest}" ]] || \
    rm -rf "${_dest}" && \
  ln -sf "${_src}" "${_dest}"
}

alias now='_now'

#
# END now
#

#
# BEGIN homebrew
#

_Homebrew_install() {
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
}

_Homebrew_uninstall() {
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  brew list | xargs brew uninstall --force
  brew list --cask | xargs brew uninstall --force
  sudo /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"
  sudo rm -rf /usr/local
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  brew list | xargs brew uninstall --force
  brew list --cask | xargs brew uninstall --force
  sudo /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"
  sudo rm -rf /usr/local
}

_Homebrew_main() {
  case "${1}" in
    "--install")
      _Homebrew_install
    ;;
    "--uninstall")
      _Homebrew_uninstall
    ;;
  esac
}

_homebrew() {
  _Homebrew_main $@
}

alias homebrew='_homebrew'

#
# END homebrew
#