#!/bin/zsh

_Zshrc_preconditions() {
  # powerlevel10k precondition
  if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]
  then
    source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
  fi
}

_Zshrc_exports() {
  # terminal
  export PROMPT="%(?:%{%}➜ :%{%}➜ ) %{$fg[cyan]%}%2~%{$reset_color%}: "
  export TERM=xterm-color
  # jenv
  export PATH="${HOME}/.jenv/bin:${PATH}"
  # snap
  export PATH="/snap/bin:${PATH}"
  # cargo
  export PATH="$HOME/.cargo/bin:$PATH"
  # dotnet tools
  export PATH=$HOME/.dotnet/tools:$PATH
  # gnu
  export GUILE_TLS_CERTIFICATE_DIRECTORY="/usr/local/etc/gnutls/"
  export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
  export PATH="/usr/local/opt/findutils/libexec/gnubin:$PATH"
  export PATH="/usr/local/opt/gnu-getopt/bin:$PATH"
  export PATH="/usr/local/opt/gnu-getopt/bin:$PATH"
  export PATH="/usr/local/opt/gnu-indent/libexec/gnubin:$PATH"
  export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"
  export PATH="/usr/local/opt/gnu-tar/libexec/gnubin:$PATH"
  export PATH="/usr/local/opt/grep/libexec/gnubin:$PATH"
  # ruby
  export PATH="/usr/local/opt/ruby/bin:$PATH"
  export LDFLAGS="-L/usr/local/opt/ruby/lib"
  export CPPFLAGS="-I/usr/local/opt/ruby/include"
  export PKG_CONFIG_PATH="/usr/local/opt/ruby/lib/pkgconfig"
}

_Zshrc_globals() {
  # terminal history
  HISTCONTROL=ignoreboth 
  HISTFILE=~/.history
  HISTFILESIZE=0
  HISTSIZE=16000
  KEYTIMEOUT=1
  SAVEHIST=15000
}

_Zshrc_setopts() {
  # setops
  setopt AUTO_NAME_DIRS # change directories  to variable names
  setopt AUTO_PUSHD  # push directories on every cd
  setopt EXTENDED_HISTORY # store time in history
  setopt HIST_EXPIRE_DUPS_FIRST # unique events are more usefull to me
  setopt HIST_VERIFY	# make those history commands nice
  setopt INC_APPEND_HISTORY # immediatly insert history into history file
  setopt NO_BEEP # self explanatory
  setopt histignoredups # ignore duplicates of the previous event
}

_Zshrc_aliases() {
  # aliases
  alias ls='ls --color=auto'
  alias grep='nocorrect grep --color=auto'
  alias fgrep='fgrep --color=auto'
  alias egrep='egrep --color=auto'
  alias ll='ls -alF'
  alias la='ls -A'
  alias l='ls -CF'
  alias cd..='cd ..'
}

_Zshrc_postconditions() {
  # colors
  autoload colors
  color_prompt=yes
  colors
  # jenv
  if which jenv > /dev/null
  then
    eval "$(jenv init -)"
  fi
  if [[ -e ${HOME}/.oh-my-zsh ]]
  then
    # oh my zsh
    source ~/.ohmyzshrc || echo 
  fi
  # powerlevel10k postcondition
  [[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh
}

_Zshrc_main() {
  _Zshrc_preconditions
  _Zshrc_setopts
  _Zshrc_globals
  _Zshrc_exports
  _Zshrc_aliases
  _Zshrc_postconditions
  source ~/.public
  source ~/.private || echo > /dev/null
}

___main___() {
    _Zshrc_main
}

___main___